### ISSUE TITLE
Thrown out bonuses should change B# in Lifsheets

### ISSUE THREAD

**Issue by alopezlago** [alopezlago/MODAQ#33]
According to this [doucment](http://minkowski.space/quizbowl/manuals/scorekeeping/moderator.html#anomalies), the way to handle bonuses read in the wrong order is to modify B#. In cases where games don't read every bonus, we should be able to modify B# ourselves. IBonusAnswerEvent tracks which bonus index was read, so we could set B# to `bonusIndex + 1`, assuming we haven't run out of bonuses.

The downside is that the guide also suggests adding a comment, and I haven't found any way to add comments through the Sheets API, and it may not be possible without some reverse-engineering.

**Comment by hftf** [comment]
For straightforward cases (such as accidentally skipping or throwing out one bonus), inserting a comment isn't necessary. But it's probably good practice to have a human (i.e. me) review all anomalies. I assume that fewer "questions read out of order" errors will occur using a dedicated reader application anyway.

Since the limited Sheets API doesn't handle comments, you can instruct the moderator to manually edit the scoresheet, saying something like "Please right-click on cell `AH12`, click `Insert comment`, and briefly explain the situation. See the [scorekeeping guide](http://minkowski.space/quizbowl/manuals/scorekeeping/moderator.html#anomalies) for instructions."

**Comment by alopezlago** [comment]
LifSheets is no longer supported, so this issue is obsolete.
