### ISSUE TITLE
At the end of a match, automatically ask/remind the moderator to export

### ISSUE THREAD

**Issue by hftf** [alopezlago/MODAQ#38]
Instead of requiring the moderator to find the "Export" button, a prompt could automatically appear at the end of a match and ask something like "Do you want to export this match to the scoresheet now?"

This may be a remedy for the mentioned behavior of moderators exporting frequently throughout a match, as they will come to expect the prompt as part of the default flow, and have a better mental model of when data actually gets "saved".

**Comment by alopezlago** [comment]
This may make sense to do after finishing some initial work on #17 , since this app should support both 20 and 24 tossup games (although Lifsheets only supports the former, so maybe we could cheat there).

**Comment by alopezlago** [comment]
#71 gets us partway there, since it now knows when a game should end. It's difficult to know when to show the prompt, though, because if there's no tie then there's no way to get to the next question, and we don't know how many points a team scores on the bonus. We could add a reminder label, or we could try moving to an auto-save model where we periodically export to the scoresheet every so often (if the user is authenticated).
